homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 23
  unit_system: metric
  time_zone: Europe/Stockholm

  customize: !include customize.yaml
  packages: !include_dir_named packages

# Enables the frontend
panel_custom: !include panel_custom.yaml

logger:
  default: info
  # logs:
  #   homeassistant.components.sensor.miflora: debug
  #   homeassistant.components.xiaomi: debug

# Enables configuration UI
config:

map:

http:
   api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
   # base_url: https://creativehackinghome.duckdns.org:8123
   # ssl_certificate: /ssl/fullchain.pem
   # ssl_key: /ssl/privkey.pem

updater:

# Discover some devices automatically
discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
# Enables support for tracking state changes over time
history:
# View all events in a logbook
logbook:
# Track the sun
sun:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml